# Preprocessing Dataset #1: Adults

In [ ]:
# age: continuous.
# workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
# fnlwgt: continuous.
# education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
# education-num: continuous.
# marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
# occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
# relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
# race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
# sex: Female, Male.
# capital-gain: continuous.
# capital-loss: continuous.
# hours-per-week: continuous.
# native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands."

In [36]:
from sklearn.preprocessing import LabelBinarizer
import numpy as np
import pandas as pd
import matplotlib as mpt 

# 1. Load the datasets into Pandas dataframes
dataset1 = pd.read_csv('adult.csv', index_col=False, names=['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'over-50K'])

# 2. Clean the data
# Replace missing values with np.nan
dataset1.loc[dataset1['age'] == 0, 'age'] = np.nan

# Remove instances with missing/invalid data entries
dataset1.dropna(axis=0, how='any')


# 2.2 Convert discrete variables into multiple variables using one-hot encoding
# dataset1['workclass'] = dataset1['workclass'].map({
#   'Private': '1000000',
#   'Self-emp-not-inc': '0100000',
#   'Self-emp-inc': '0010000',
#   'Federal-gov': '0001000',
#   'Local-gov': '0000100',EWn
#   'State-gov': '0000010',
#   'Without-pay': '0000001',
#   'Never-worked': '0000000',
# }.get)

y = LabelBinarizer().fit_transform(dataset1.workclass)
print(y)



[[0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
# Split into training, validation, and tests